name: Deploy Astro to GitHub Pages

on:
  push:
    branches: [main]

# اضافه کردن این بخش برای حل خطای دسترسی
permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install & Build
        uses: withastro/action@v2

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist